name: user_repository
description: This package handles users
publish_to: 'none'

environment:
  sdk: '>3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
